spring:
  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: notification
    schema-action: CREATE_IF_NOT_EXISTS
    request.timeout: 10s
    connection.connect-timeout: 10s
    connection.init-query-timeout: 10s